[project]
name = "pyimgbox"
description = "API for uploading images to imgbox.com"
readme = "README.md"
license = {text = "GPL-3.0-or-later"}
authors = [
  { name="plotski", email="plotski@example.org" },
]
dynamic = ["version"]  # Get version from PROJECT/__version__
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Intended Audience :: Developers",
]
requires-python = ">=3.8"
dependencies = [
    "httpx==0.*",
    "beautifulsoup4",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-mock",
    "pytest-httpserver",

    "tox",

    "coverage",
    "pytest-cov",

    "ruff",
    "flake8",
    "isort",
]

[project.urls]
Repository = "https://codeberg.org/plotski/pyimgbox"
"Bug Tracker" = "https://codeberg.org/plotski/pyimgbox/issues"
Changelog = "https://codeberg.org/plotski/pyimgbox/raw/branch/master/NEWS"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# For some unknown reason, we need to specify explicity to scan the project
# directory with default parameters or setuptools gets confused about
# directories like "docs" or "venv".
[tool.setuptools.packages]
find = {}

[tool.setuptools.dynamic]
version = {attr = "pyimgbox.__version__"}
