[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "windmill_client"
description = "A client for the Windmill API"
readme = "README.md"
authors = [{name = "Stephan Fitzpatrick", email = "knowsuchagency@gmail.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
version = "0.7.0"
dependencies = [
    "httpx~=0.25",
]
