[tool.poetry]
name = "algo-trading-utils"
version = "0.0.13"
description = ""
authors = ["jamesbaber1 <31859220+jamesbaber1@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "algo_trading_utils"}]

[tool.poetry.dependencies]
python = ">=3.9,<4.0.0"
tickerdax = ">=0.0.83"
psycopg2-binary = ">=2.9.7"
pandas = "^2.1.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
