[tool.poetry]
name = "fastapi_toolkit_shawn587"
version = "0.2.1.3"
authors = ["0x587 <shawnsiu@outlook.com>"]
description = "This toolkit can generate database CRUD operations based on defined metadata in one click, basic fastapi routing and mock data scripts."
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [{include = "fastapi_toolkit"}]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.104.1"
fastapi-pagination = "^0.12.12"
sqlalchemy = "^2.0.23"
jinja2 = "^3.1.2"
typer = {extras = ["all"], version = "^0.9.0"}
faker = "^20.0.3"
psycopg2-binary = "^2.9.9"
asyncpg = "^0.29.0"
alembic = "^1.12.1"
pydantic = "^2.5.1"
pyyaml = "^6.0.1"
fastapi-users = {extras = ["sqlalchemy"], version = "^12.1.2"}
uvicorn = "^0.24.0.post1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
