name: auto reference update ğŸ”„

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["macos ğŸ", "ubuntu ğŸ§", "windows ğŸªŸ"]
    types: [completed]

jobs:
  update_reference:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ref_folder: 'references/linux'
          - os: macos-latest
            ref_folder: 'references/darwin'
          - os: windows-latest
            ref_folder: 'references/windows'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pytest

      - name: Pull latest changes
        run: |
          git pull origin ${{ github.event.pull_request.head.ref || github.ref_name }}
                  
      - name: Commit Reference
        if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
                 (github.event_name == 'pull_request' && github.base_ref == 'main') ||
                 (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
        run: |
          git config --global user.name 'TheBundle'
          git config --global user.email 'noreply@github.com'
          git add ${{ matrix.ref_folder }}
          git diff --quiet && git diff --staged --quiet || git commit -m "auto: update references for '${{ matrix.os }}'"
          git push --set-upstream https://${{ secrets.GITACTION_ACCESS_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.event.pull_request.head.ref || github.ref_name }}
