variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

################################################################################
# PIP
################################################################################
build-pip:
  image: python:3.11
  cache:
    paths:
      - .cache/pip
  before_script:
    - python --version ; pip --version  # for debugging purposes
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install build
  script:
    - python -m build
  artifacts:
    paths:
      - dist/*

test-pip:
  image: python:3.11
  cache:
    paths:
      - .cache/pip
  before_script:
    - python --version ; pip --version  # for debugging purposes
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install build
  needs:
    - job: build-pip
      artifacts: true
  before_script:
    - python -m pip install dist/pydft-*.whl
    - python -m pip install numpy scipy matplotlib pytest pyqint pylebedev mendeleev tqdm
  script:
    - python -m pytest tests/*

deploy-pip:
  image: python:3.11
  cache:
    paths:
      - .cache/pip
  before_script:
    - python --version ; pip --version  # for debugging purposes
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  needs:
    - job: build-pip
      artifacts: true
    - job: test-pip
  before_script:
    - python -m pip install twine
  script:
    - twine upload -u __token__ -p ${pypi_token} dist/*

deployment-pip-verification:
  image: python:3.11
  cache:
    paths:
      - .cache/pip
  before_script:
    - python --version ; pip --version  # for debugging purposes
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  needs:
    - job: deploy-pip
  before_script:
    - python -m pip install numpy scipy matplotlib pytest pydft
  script:
    - pytest tests

################################################################################
# ANACONDA
################################################################################
build-conda:
  image: continuumio/miniconda3:23.10.0-1
  before_script:
    - rm pyproject.toml                        # ignore pyproject.toml file
    - conda install conda-build
    - conda install -c ifilot pyqint pylebedev # needed for testing
    - conda install -c conda-forge tqdm        # needed for testing
  script:
    - conda build . --output-folder conda-bld/
  artifacts:
    paths:
      - conda-bld/noarch/*

deploy-anaconda:
  image: continuumio/miniconda3:23.10.0-1
  before_script:
    - rm pyproject.toml                        # ignore pyproject.toml file
    - conda install anaconda-client
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  needs:
    - job: build-conda
      artifacts: true
  script:
    - anaconda -t ${anaconda_token} upload -u ${anaconda_user} conda-bld/noarch/pydft-*.tar.bz2