[project]
name = "django-silica"
description = "A reusable Django app for Silica functionalities."
readme = "README.md"
version = "0.1.23"
classifiers = [ "Development Status :: 3 - Alpha", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3.10", "Framework :: Django",]
keywords = [ "django", "silica", "reusable", "app",]
requires-python = ">=3.8, <4"
dependencies = [ "shortuuid~=1.0.11", "beautifulsoup4~=4.12.2",]
[[project.authors]]
name = "Dyvenia"

[build-system]
build-backend = "flit_core.buildapi"
requires = [ "flit_core >=3.2,<4",]

[project.optional-dependencies]
test = [ "pytest>=7.1,<8.0", "pytest-cov>=3.0,<4", "coverage>=6.4,<7", "selenium~=4.13.0", "chromedriver-py~=117.0.5938.92", "webdriver-manager~=4.0.1",]

[tool.setuptools]
packages = [ "django-silica",]

[tool.black]
line-length = 88
exclude = "/(\n    \\.git\n  | \\.mypy_cache\n  | \\.tox\n  | \\.venv\n  | _build\n  | buck-out\n  | build\n  | dist\n  | venv\n)/\n"

[tool.isort]
profile = "black"
