[tool.poetry]
name = "wizlib"
version = "2.0.8"
description = "Framework for flexible and powerful command-line applications"
authors = ["Steampunk Wizard <wizlib@steampunkwizard.ca>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
PyYAML = "^6.0.1"
pyreadline3 = { version="^3.4.1", markers="sys_platform=='win32'" }
gnureadline = { version="^8.1.2", markers="sys_platform=='darwin'" }

[tool.poetry.group.dev.dependencies]
coverage = "^7.3.1"
pycodestyle = "^2.11.0"
autopep8 = "^2.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
format = "{base}"

