[tool.poetry]
name = "reach_commons"
version = "0.6.2"
description = "Uma descrição curta da biblioteca"
authors = ["Wilson Moraes <wmoraes@getreach.ai>"]
license = "MIT"
readme = "README.md"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.8"
pip="23.3.1"
setuptools="68.2.2"
wheel="0.41.2"
requests="2.31.0"
twine="4.0.2"
boto3="1.28.68"
botocore="^1.31.68"

[tool.poetry.dev-dependencies]
black="23.10.0"
isort="5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"