[project]
name = "django_rest_framework_query_tools"
version = "0.0.21"
authors = [
  { name="Joe Philip", email="joe.philip@hotmail.co.in" },
]
description = "A small package that help you filter list api responses from frontend using query parameters."
readme = "README.md"
requires-python = ">=3.8.16"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/joe-philip/django-query-tools"
Issues = "https://github.com/joe-philip/django-query-tools/issues"

[build-system]
requires = ["djangorestframework>=3.14.0", "toml"]
build-backend = "hatchling.build"