[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qrstu"
dynamic = ["version"]
description = "Q – Rainer Schwarzbach’s Text Utilities"
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
keywords = [
  "text",
  "unicode",
  "convert",
  "transcode",
]
authors = [
  {name = "Rainer Schwarzbach", email = "rainer@blackstream.de"},
]
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
]

[project.urls]
Homepage = "https://gitlab.com/blackstream-x/qrstu"
Documentation = "https://blackstream-x.gitlab.io/qrstu"
CI = "https://gitlab.com/blackstream-x/qrstu/-/pipelines"
"Bug Tracker" = "https://gitlab.com/blackstream-x/qrstu/-/issues"
Repository = "https://gitlab.com/blackstream-x/qrstu.git"

[tool.setuptools.dynamic]
version = {attr = "qrstu.__version__"}

[tool.setuptools.package-data]
"qrstu" = ["py.typed"]

