[tool.poetry]
name = "notion-calendar-generator"
version = "0.0.1"
description = ""
authors = ["attila szuts <45080765+attilaszuts@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "notion_calendar_generator"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
click = "^8.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
nocage = "main:main"
