[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ModuleDB"
version = "0.0.0.1"
description = ""
authors = [{name = "lcctoor.com", email = "lcctoor@outlook.com"}]