[project]
name = "bw-sdk"
version = "0.1.12"
description = ""
authors = [
    { name = "Kalle M. Aagaard", email = "git@k-moeller.dk" },
]
dependencies = [
    "httpx>=0.25.0",
    "pydantic>=2.4.2",
]
requires-python = ">=3.12"
readme = "README.md"

[project.license]
text = "MIT"

[project.urls]
Repository = "https://github.com/KalleDK/py-bitwarden-sdk"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.3",
    "pytest-cov>=4.1.0",
]
dev = [
    "black>=23.10.1",
    "mypy>=1.6.1",
    "ruff>=0.1.3",
    "bump2version>=1.0.1",
    "python-dotenv>=1.0.0",
]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.black]
line-length = 120

[tool.pyright]
include = [
    "src/bw_sdk",
    "tests",
    "examples",
]

[tool.pytest.ini_options]
addopts = "-v --cov=bw_sdk --cov-report=term-missing --cov-report=xml"
testpaths = [
    "tests",
]

[tool.coverage.report]
exclude_also = [
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]

[tool.mypy]
python_version = "3.12"
packages = "bw_sdk"
mypy_path = "typings"
